// Generated by gencpp from file robotrun/op_armResponse.msg
// DO NOT EDIT!


#ifndef ROBOTRUN_MESSAGE_OP_ARMRESPONSE_H
#define ROBOTRUN_MESSAGE_OP_ARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotrun
{
template <class ContainerAllocator>
struct op_armResponse_
{
  typedef op_armResponse_<ContainerAllocator> Type;

  op_armResponse_()
    : feedmsg()  {
    }
  op_armResponse_(const ContainerAllocator& _alloc)
    : feedmsg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedmsg_type;
  _feedmsg_type feedmsg;





  typedef boost::shared_ptr< ::robotrun::op_armResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotrun::op_armResponse_<ContainerAllocator> const> ConstPtr;

}; // struct op_armResponse_

typedef ::robotrun::op_armResponse_<std::allocator<void> > op_armResponse;

typedef boost::shared_ptr< ::robotrun::op_armResponse > op_armResponsePtr;
typedef boost::shared_ptr< ::robotrun::op_armResponse const> op_armResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotrun::op_armResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotrun::op_armResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotrun

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotrun': ['/home/lsf/LSF/cruiserobot_ws/src/robotrun/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotrun::op_armResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotrun::op_armResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotrun::op_armResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotrun::op_armResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotrun::op_armResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotrun::op_armResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotrun::op_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c15f042b3c8741e7bbc6b472300f5ee";
  }

  static const char* value(const ::robotrun::op_armResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c15f042b3c8741eULL;
  static const uint64_t static_value2 = 0x7bbc6b472300f5eeULL;
};

template<class ContainerAllocator>
struct DataType< ::robotrun::op_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotrun/op_armResponse";
  }

  static const char* value(const ::robotrun::op_armResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotrun::op_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string feedmsg\n\
";
  }

  static const char* value(const ::robotrun::op_armResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotrun::op_armResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedmsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct op_armResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotrun::op_armResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotrun::op_armResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedmsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTRUN_MESSAGE_OP_ARMRESPONSE_H
