// Generated by gencpp from file robotrun/op_armRequest.msg
// DO NOT EDIT!


#ifndef ROBOTRUN_MESSAGE_OP_ARMREQUEST_H
#define ROBOTRUN_MESSAGE_OP_ARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotrun
{
template <class ContainerAllocator>
struct op_armRequest_
{
  typedef op_armRequest_<ContainerAllocator> Type;

  op_armRequest_()
    : stopThreshold(0)
    , travelDirection(0)  {
    }
  op_armRequest_(const ContainerAllocator& _alloc)
    : stopThreshold(0)
    , travelDirection(0)  {
  (void)_alloc;
    }



   typedef int32_t _stopThreshold_type;
  _stopThreshold_type stopThreshold;

   typedef int32_t _travelDirection_type;
  _travelDirection_type travelDirection;





  typedef boost::shared_ptr< ::robotrun::op_armRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotrun::op_armRequest_<ContainerAllocator> const> ConstPtr;

}; // struct op_armRequest_

typedef ::robotrun::op_armRequest_<std::allocator<void> > op_armRequest;

typedef boost::shared_ptr< ::robotrun::op_armRequest > op_armRequestPtr;
typedef boost::shared_ptr< ::robotrun::op_armRequest const> op_armRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotrun::op_armRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotrun::op_armRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotrun

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotrun': ['/home/lsf/LSF/cruiserobot_ws/src/robotrun/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotrun::op_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotrun::op_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotrun::op_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotrun::op_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotrun::op_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotrun::op_armRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotrun::op_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33d66904a6cbb0e030f3253e2c1c9fad";
  }

  static const char* value(const ::robotrun::op_armRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33d66904a6cbb0e0ULL;
  static const uint64_t static_value2 = 0x30f3253e2c1c9fadULL;
};

template<class ContainerAllocator>
struct DataType< ::robotrun::op_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotrun/op_armRequest";
  }

  static const char* value(const ::robotrun::op_armRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotrun::op_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 stopThreshold\n\
int32 travelDirection\n\
";
  }

  static const char* value(const ::robotrun::op_armRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotrun::op_armRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stopThreshold);
      stream.next(m.travelDirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct op_armRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotrun::op_armRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotrun::op_armRequest_<ContainerAllocator>& v)
  {
    s << indent << "stopThreshold: ";
    Printer<int32_t>::stream(s, indent + "  ", v.stopThreshold);
    s << indent << "travelDirection: ";
    Printer<int32_t>::stream(s, indent + "  ", v.travelDirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTRUN_MESSAGE_OP_ARMREQUEST_H
